--- name:default
loadFilename: '/home/dimi/rock_bags/ebee/densified_cloud.ply'
saveFilename: '/home/dimi/rock_bags/ebee/densified_cloud.pcd'
savePreprocessedCloud: true
smoothCloud: true
sorMeanK: 50
sorStdMultiplier: 0.8
cloudYawOffset: -1.5707
cloudEastingOffset: 344178.0
cloudNorthingOffset: 3127579.0
cloudElevationOffset: 2442.0
robotEastingOffset: 344039.8
robotNorthingOffset: 3127408.3
robotElevationOffset: 2543.0
# robotEastingOffset: 344043.0
# robotNorthingOffset: 3127403.0
# robotElevationOffset: 2296.0

--- name:prepared
loadFilename: '/home/dimi/rock_bags/ebee/densified_cloud.pcd'
preprocessingEnabled: false

