--- name:default
loadFilename: '/home/dimi/rock_bags/ebee/densified_cloud.ply'
savePreprocessedCloud: true
saveFilename: '/home/dimi/rock_bags/ebee/densified_cloud.pcd'
voxelSize: 1.0
sorMeanK: 50
sorStdMultiplier: 0.8
rotation:
    data:
        - 0.0
        - 0.0
        - 0.0
translation:
    data:
        - 0.0
        - 0.0
        - 100.0
box:
    data:
        - 100.0
        - 100.0
        - 1000.0

--- name:prepared
loadFilename: '/home/dimi/rock_bags/ebee/densified_cloud.pcd'
preprocessingEnabled: false

