--- name:default
mapLengthX: 8.0
mapLengthY: 8.0
mapResolution: 0.05
minElevation: -5.0
maxElevation: 5.0
voxelSize: 0.05
numParticles: 100
initialSigmaX: 0.0
initialSigmaY: 0.0
initialSigmaYaw: 0.0
predictSigmaX: 0.05
predictSigmaY: 0.05
predictSigmaYaw: 3.14/36

--- name:test
debugInfoEnabled: true
rawMapDebugEnabled: true
cloudDebugEnabled: false
serializationDebugEnabled: true
mapLengthX: 20.0
mapLengthY: 20.0
mapResolution: 0.2
minElevation: -2.0
maxElevation: 2.0
voxelSize: 0.2
numParticles: 1
resampleFrequency: 5
initialSigmaX: 0.0
initialSigmaY: 0.0
initialSigmaYaw: 0.0
predictSigmaX: 0.0
predictSigmaY: 0.0
predictSigmaYaw: 0.0

