--- name:default
mapSizeX: 10.0
mapSizeY: 10.0
robotPositionX: 0.0
robotPositionY: 0.0
mapResolution: 0.050
voxelSize: 0.025
minElevation: -5.0
maxElevation: 5.0

--- name:test
mapSizeX: 4.0
mapSizeY: 4.0
robotPositionX: 4.0
robotPositionY: 0.0
mapResolution: 0.10
voxelSize: 0.05
minElevation: -2.0
maxElevation: 2.0

