--- name:default
mapSizeX: 8.0
mapSizeY: 8.0
robotPositionX: 0.0
robotPositionY: 0.0
mapResolution: 0.05
voxelSize: 0.05
minElevation: -5.0
maxElevation: 5.0

--- name:test
debugInfoEnabled: true
rawMapDebugEnabled: true
pointCloudDebugEnabled: false
serializationDebugEnabled: true
mapSizeX: 20.0
mapSizeY: 20.0
robotPositionX: 0.0
robotPositionY: 0.0
mapResolution: 0.2
voxelSize: 0.2
minElevation: -2.0
maxElevation: 2.0

